// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTuq_d69-K4BAjjVeBMZTlzZo1R7YEdYo',
    appId: '1:787285180570:web:dc89f0c5859b657e6b5f23',
    messagingSenderId: '787285180570',
    projectId: 'dusto-3d660',
    authDomain: 'dusto-3d660.firebaseapp.com',
    storageBucket: 'dusto-3d660.firebasestorage.app',
    measurementId: 'G-XW7FSVHDWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9npCkU0mjUUBOWi2UU9h1Q32xUZ6ASk',
    appId: '1:787285180570:android:6819109d13d2e34d6b5f23',
    messagingSenderId: '787285180570',
    projectId: 'dusto-3d660',
    storageBucket: 'dusto-3d660.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMe_dvHJrNjj_0SZ21kl74ocP8JL7lGwM',
    appId: '1:787285180570:ios:f4dff54e2de4bb796b5f23',
    messagingSenderId: '787285180570',
    projectId: 'dusto-3d660',
    storageBucket: 'dusto-3d660.firebasestorage.app',
    iosBundleId: 'com.r3infosolutions.dusto',
  );

}